# Generated by Django 4.2.5 on 2023-10-04 08:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='banner',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
    ]
