# Generated by Django 4.2.5 on 2023-12-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tx_hash',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
