# Generated by Django 4.2.5 on 2023-11-19 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.CharField()),
                ('avatar', models.ImageField(blank=True, upload_to='traceability/')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_decriptions', to='product.product')),
            ],
        ),
    ]
