# Generated by Django 4.2.5 on 2023-11-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_description', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detaildescription',
            old_name='avatar',
            new_name='image',
        ),
    ]
