# Generated by Django 4.2.5 on 2023-11-13 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_create_by'),
        ('growup', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growup',
            name='image',
        ),
        migrations.AlterField(
            model_name='growup',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='growup', to='product.product'),
        ),
    ]
