# Generated by Django 4.2.5 on 2023-12-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growup', '0003_remove_growup_image_alter_growup_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growup',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='growup',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
