# Generated by Django 4.2.5 on 2023-12-19 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDDING', 'PENDDING'), ('ACCEPT', 'ACCEPT'), ('REJECT', 'REJECT'), ('DONE', 'DONE')], default='PENDDING', max_length=255)),
                ('is_reject', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_product', to='product.product')),
            ],
        ),
    ]
