# Generated by Django 4.2.5 on 2023-11-21 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_is_delete'),
        ('transaction', '0003_remove_transaction_status_transaction_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_product', to='product.product'),
        ),
    ]
