# Generated by Django 4.2.5 on 2023-11-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_transaction_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDDING', 'PENDDING'), ('ACCEPT', 'ACCEPT'), ('PENDDING', 'PENDDING'), ('REJECT', 'REJECT')], default='PENDDING'),
        ),
    ]
