# Generated by Django 4.2.5 on 2023-11-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDDING', 'PENDDING'), ('ACCEPT', 'ACCEPT'), ('REJECT', 'REJECT'), ('DONE', 'DONE')], default='PENDDING'),
        ),
    ]
