# Generated by Django 4.2.5 on 2023-12-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDDING', 'PENDDING'), ('ACCEPT', 'ACCEPT'), ('REJECT', 'REJECT'), ('DONE', 'DONE')], default='PENDDING', max_length=255),
        ),
    ]
