# Generated by Django 4.2.5 on 2023-11-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_confirm_status_user_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'MEMBER'), ('FARMER', 'FARMER'), ('SEEDLING_COMPANY', 'SEEDLING_COMPANY'), ('FACTORY', 'FACTORY'), ('DISTRIBUTER', 'DISTRIBUTER')], default='MEMBER'),
        ),
    ]
