# Generated by Django 4.2.5 on 2023-11-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'MEMBER'), ('FISHERMEN', 'FISHERMEN'), ('SEEDLING_COMPANY', 'SEEDLING_COMPANY'), ('FACTORY', 'FACTORY'), ('DISTRIBUTER', 'DISTRIBUTER')], default='MEMBER'),
        ),
    ]
