# Generated by Django 4.2.5 on 2023-11-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_introduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'MEMBER'), ('FACTORY', 'FACTORY'), ('DISTRIBUTER', 'DISTRIBUTER'), ('RETAILER', 'RETAILER')], default='MEMBER'),
        ),
    ]
