# Generated by Django 4.2.5 on 2023-11-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
