# Generated by Django 4.2.5 on 2023-11-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_status',
            field=models.CharField(choices=[('NONE', 'NONE'), ('PENDDING', 'PENDDING'), ('DONE', 'DONE')], default='NONE'),
        ),
    ]
