# Generated by Django 4.2.5 on 2023-12-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_confirm_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tx_hash',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_private_key',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
