# Generated by Django 4.2.5 on 2023-12-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_tx_hash_user_wallet_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_status',
            field=models.CharField(choices=[('NONE', 'NONE'), ('PENDDING', 'PENDDING'), ('DONE', 'DONE')], default='NONE', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'MEMBER'), ('FACTORY', 'FACTORY'), ('DISTRIBUTER', 'DISTRIBUTER'), ('RETAILER', 'RETAILER')], default='MEMBER', max_length=255),
        ),
    ]
