# Generated by Django 4.2.5 on 2023-11-14 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_alter_product_create_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='product.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
