# Generated by Django 4.2.5 on 2023-11-20 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['create_at']},
        ),
    ]
