# Generated by Django 4.2.5 on 2023-11-20 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='product',
            new_name='user',
        ),
    ]
