# Generated by Django 4.2.5 on 2023-11-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_image', '0002_rename_product_userimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='traceability/'),
        ),
    ]
