# Generated by Django 4.2.5 on 2023-12-19 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grow_up_image', '0001_initial'),
        ('growup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='growupimage',
            name='growup_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growup_images', to='growup.growup'),
        ),
    ]
