# Generated by Django 4.2.5 on 2023-11-13 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('growup', '0003_remove_growup_image_alter_growup_product_id'),
        ('grow_up_image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growupimage',
            name='product',
        ),
        migrations.AddField(
            model_name='growupimage',
            name='growup_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='growup_images', to='growup.growup'),
            preserve_default=False,
        ),
    ]
