# Generated by Django 4.2.5 on 2023-11-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow_up_image', '0002_remove_growupimage_product_growupimage_growup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growupimage',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='traceability/'),
        ),
    ]
